# Generated by Django 2.2.16 on 2022-06-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220602_1502'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='author_title',
        ),
    ]
