# Generated by Django 2.2.16 on 2022-06-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220602_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Отзыв',), 'verbose_name_plural': 'Отзывы'},
        ),
    ]
