# Generated by Django 2.2.16 on 2022-06-06 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220604_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, 'минимальная оценка 1'), django.core.validators.MaxValueValidator(10, 'максимальная оценка 10')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
    ]
